# Generated by Django 3.0.4 on 2020-04-21 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zak', '0003_auto_20200412_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zak',
            name='child',
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kidname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='zak',
            name='kidname',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='zak.Kid'),
        ),
    ]
