# Generated by Django 3.0.4 on 2020-04-21 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zak', '0004_auto_20200421_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zak',
            name='kidname',
        ),
        migrations.AddField(
            model_name='zak',
            name='child',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Kid',
        ),
    ]
