# Generated by Django 3.0.4 on 2020-03-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minizakgeld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakgeld',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
